### ISSUE TITLE
Trying to add typescript to my test package

### ISSUE THREAD

**Issue by YashdalfTheGray** [smhxx/atom-ts-transpiler#8]
Hello, maybe I'm doing something wrong but I'm trying to use `atom-ts-transpiler` with my Atom package and here's what I've added to my `package.json`

```json
"atomTranspilers": [
    {
      "glob": "(lib|spec)/**/*.ts",
      "transpiler": "atom-ts-transpiler"
    }
  ]
```

I'm using macOS sierra 10.12.6, Atom 1.21.0, Typescript 2.5.3, Node 8.6.0 and `atom-ts-compiler` 1.1.0 but when I try to activate my package, I get the error below. I see that this error is caused by the `lib.d.ts` file being moved as mentioned [here](https://github.com/andreypopp/typescript-loader/issues/26). 

![image](https://user-images.githubusercontent.com/3102848/31158843-86dc893a-a879-11e7-9116-4deb95d386f3.png)

This is what happens when I run `tsc` in the folder where the package is located (I don't know if this is valuable or not)

```
$ tsc
node_modules/electron/electron.d.ts(788,18): error TS2304: Cannot find name 'webContents'.
node_modules/electron/electron.d.ts(2646,5): error TS2300: Duplicate identifier 'workingSetSize'.
node_modules/electron/electron.d.ts(2650,5): error TS2300: Duplicate identifier 'workingSetSize'.
node_modules/electron/electron.d.ts(5662,5): error TS2300: Duplicate identifier 'false'.
node_modules/electron/electron.d.ts(5662,13): error TS2304: Cannot find name 'by'.
node_modules/electron/electron.d.ts(5666,5): error TS2300: Duplicate identifier 'false'.
node_modules/electron/electron.d.ts(5666,13): error TS2304: Cannot find name 'by'.
node_modules/electron/electron.d.ts(7696,27): error TS2304: Cannot find name 'CPUUsage'.
node_modules/electron/electron.d.ts(7697,31): error TS2304: Cannot find name 'IOCounters'.
```

**Comment by smhxx** [comment]
What other packages does your project depend upon? The fact that something is even trying to access `node_modules/typescript/bin/lib.d.ts` seems to suggest that some package is expecting to be working with TypeScript ~1.5 and is instead given a more recent version where the core library defs are in a different location.

Also, for the record, I don't think you should need `spec` in your glob (although it shouldn't hurt anything, I suppose.) `atom-ts-transpiler` only affects files that Atom requires at runtime, which probably doesn't include your test suite. As long as *you're* able to run your tests, that should be sufficient, so `lib/**/*.ts` is all you really need.

**Comment by GlenCFL** [comment]
This is actually an issue with ``@types/atom```. DefinitelyTyped requires us to depend on Electron directly, yet the electron type definitions can contain errors due to being automatically generated.

I was actually trying to fix this in [this pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20240). It still will be fixed on way or another, as there's no way ```@types/atom``` is going to continue depending on Electron directly.

**Comment by GlenCFL** [comment]
The output of TSC is an issue with ```@types/atom```, that is.

**Comment by GlenCFL** [comment]
I actually cant get the TypeScript variant of the transpiler to work either, whereas the previous JS version worked perfectly. Atom is not redirecting the TS source files to this package and is instead using the default TypeScript transpiler, which is [typescript-simple v1.0](https://github.com/teppeis/typescript-simple/tree/v1.0.0) (TS version ~1.4.1).

**Comment by smhxx** [comment]
Huh... that's interesting. I think I may know why that's happening, I'll
look into it and get a fix out. That also explains where that
`bin/lib.d.ts` from TypeScript <1.5 is coming into play, if Atom is trying
to use an older version to run the files.

It seems to me that you're correct and this is actually two separate
issues. One I may be able to fix really easily, but the other (concerning
Electron's bundled typedefs) may be somewhat more difficult to address.
I'll also do some investigating into that and see if a potential solution
jumps out at me.

**Comment by smhxx** [comment]
@GlenCFL Okay, this is strange... I actually can't repro that on 1.1.0 *or* the bleeding-edge version from the repo. Are you getting any relevant error messages on the Ctrl+Shift+D console?

**Comment by GlenCFL** [comment]
The second issue was resolved with ```@types/atom@1.21```. Electron was just removed, with that single reference now being an object.

I'm still gathering information. It's an odd bug in that it vanishes when I removed getCacheKeyData() from the JS entirely, yet didn't resurface whenever I added it back in. Everything seems to be working correctly elsewhere, so it resolves the correct TS version and compiles the code successfully. It's just something revolving around that function.

**Comment by GlenCFL** [comment]
I cant replicate it anymore, even with the Atom compiler cache being cleared.

**Comment by smhxx** [comment]
Ah, clever workaround. I understand DT's reluctance to host typedefs for projects that bundle their own, but requiring a 140 MB module as a dependency just to grab a 300 KB typedef file is... kind of silly. Ultimately, I don't think there's much direct interaction between package code and Electron, so it's not much of a sacrifice. Not sure what was causing the weirdness with the transpiler not being called by Atom, but I'm sure we'll get more info if and when it happens to anybody else.

@YashdalfTheGray, can you bump your project up to `@types/atom` 1.21.0 and share:

1. Any `tsc` errors that still exist (should be fixed with typedefs update)
2. Any error notifications shown by Atom, if different from the original one
3. Any errors logged to the Ctrl+Shift+D developer console?

**Comment by smhxx** [comment]
@YashdalfTheGray Also, I'm just now realizing that your glob isn't going to match any files, which may be related to the issue you're experiencing. I'd recommend changing it to one of these:

- `**/*.ts` (since files are transpiled lazily, there's no loss from being too general... unless there are .ts files that you *don't* want transpiled if they are required, for some reason)
- `lib/**/*.ts` (also okay, provided that all your package's runtime .ts files are in the lib directory)
- `+(lib|spec)/**/*.ts` (you probably don't need to be this specific, and your spec files almost certainly aren't required from your program itself)

A general rule of thumb for specifying the glob for your transpiler entry is that "too general" is almost always okay, since files aren't transpiled until they're needed. Any file matching the glob that *doesn't* get required during normal operation of your package, such as your test suite, won't be transpiled at all. If you need to be more specific, because you have .ts files that you want to be passed to Atom *without* transpilation for some reason, you can use [GlobTester](http://www.globtester.com) to check that your glob is targeting the right files and excluding others.

**Comment by GlenCFL** [comment]
The transpiler was being called by Atom whenever I had that problem. The transpiler itself would correctly find the local TS, compile, and output that object without any issues. It was after that point that Atom still decided to use the default transpiler.

**Comment by smhxx** [comment]
Well that's weird. I wonder if that's an Atom bug? Not really sure. Maybe #9 will help diagnose the issue if it recurs.

**Comment by YashdalfTheGray** [comment]
Oh I missed all of this really good discussion! Alright, I'm updating my Atom typings to `1.21.0`. A question about the glob, would adding `**/*.ts` mean that I'm also transpiling stuff under `node_modules`? And how would I write my tests in Typescript as well or is that generally not done?

Here's the list of dependencies that I have in my package. It's not much at this point since I'm just testing stuff out right now but I don't expect to add a lot of other ones. 

```
  "dependencies": {
    "@types/atom": "1.21.0",
    "atom-ts-transpiler": "1.1.0",
    "bluebird": "3.5.0",
    "request": "2.83.0",
    "request-promise": "4.2.2",
    "typescript": "2.5.3"
  },
  "devDependencies": {
    "eslint": "4.7.2",
    "eslint-config-airbnb-base": "12.0.0",
    "eslint-plugin-import": "2.7.0",
    "proxyquire": "1.8.0"
  }
```

**Comment by YashdalfTheGray** [comment]
Alright, I changed my Atom typings to `1.21.0` and I get this error still (which is the same error that I was getting, it's just now in the console rather than a popup like yesterday). 

```
ENOENT, node_modules/typescript/bin/lib.d.ts not found in /Applications/Atom.app/Contents/Resources/app.asar Error: ENOENT, node_modules/typescript/bin/lib.d.ts not found in /Applications/Atom.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:514:9)
    at TypeScriptSimple.createService (/Applications/Atom.app/Contents/Resources/app/node_modules/typescript-simple/index.js:71:73)
    at TypeScriptSimple.compile (/Applications/Atom.app/Contents/Resources/app/node_modules/typescript-simple/index.js:60:43)
    at Object.exports.compile (/Applications/Atom.app/Contents/Resources/app/src/typescript.js:54:53)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:79:33)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:97:37)
    at Object.value [as .ts] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/yash/git-yash/atom-ecs/lib/atom-ecs.js:4:38)
    at Object.<anonymous> (/Users/yash/git-yash/atom-ecs/lib/atom-ecs.js:49:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at new PackageCard (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:92:16)
    at InstalledPackagesPanel.createPackageCard (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-packages-panel.js:413:20)
    at ListView.module.exports.ListView.addView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/list-view.js:50:25)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/list-view.js:13:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at List.module.exports.List.setItems (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/list.js:44:28)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-packages-panel.js:375:33
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by YashdalfTheGray** [comment]
@smhxx also, I might dig into this issue a little bit tonight and see what I come up with. Also, I'm sorry I missed that there was an issues template.

**Comment by smhxx** [comment]
No, it's not your fault. I committed it after you opened the issue, otherwise it would have been pulled in automatically.

File globs are resolved from your package's root directory (where the package.json is located) so I believe it technically would include your node_modules folder, unless Atom guards for that internally. I'd have to check. Either way, it's unlikely to cause problems since the glob will only match TypeScript files anyway. If you wanted to be extra sure, you could use a glob like `{!(node_modules)**/*.ts{,x},*.ts{,x}}` which will match any .ts or.tsx files that are not descendants of any node_modules folder. I may end up putting that glob in the README as the "default" suggestion, to be honest.

As for testing, you can write your tests in JS, TS, CoffeeScript, whatever you want. `atom-ts-transpiler` doesn't care since it only deals with files that Atom uses at runtime. Essentially, the function of the `atomTranspilers` entry in package.json is to tell Atom, "If you need to run/require any files in this package that look like <glob>, ask *this* package and it will turn them into JavaScript for you." Since Atom never accesses your test suite, the language your tests are written in doesn't affect its operation at all. It's just a matter of personal preference.

As for the error messages, I'll take a look at your dependencies and make sure the cause isn't external, then dig a little deeper and see if I can suss out where this older TypeScript version stuff is coming from. Thanks for the additional info. :+1:

**Comment by GlenCFL** [comment]
@YashdalfTheGray
I'm not sure if the default jasmine test runner within Atom can actually run tests written in TypeScript. So far, I haven't had any luck getting TS files within spec to actually register with it.

I'm going to try to get a custom Mocha test runner working with this transpiler, which is what the [Github](https://github.com/atom/github) atom package uses for its tests. They've written a custom runner already, so most of the hard work is done.

**Comment by YashdalfTheGray** [comment]
@smhxx yeah, no problem. I've changed the glob to `lib/**/*.ts` for now but I might switch to your suggestion. It ultimately expresses what I want to include perfectly. I've been looking around in my dependencies to see if any of that depends on Typescript <1.5. I figured since I had the npm5 `package-lock.json` file, I could search for `typescript` and look at all the versions included but I haven't found anything useful at this point. 

@GlenCFL oh if I can move away from Jasmine (what seems like 1.3), it would be amazing! I would love to write tests in something like `tape` or `ava` but I also understand that it's probably not really good with UI related tests (never written `tape` or `ava` tests involving a UI personally). But yeah, just having a more up to date test runner would be :100:!

**Comment by smhxx** [comment]
OH, now I get it. You've been talking about `apm test`, not running your own unit tests locally before deployment. Now I understand why you had `spec` in your glob. I haven't done any research into whether apm respects the `atomTranspiler` settings in the package.json file... that use case hadn't even crossed my mind, although I understand now why it would be desirable. The unit tests for this repo (which is, of course, an *npm* package, not an *apm* package) use Jest, which seemed like the most straightforward option for tests written in TypeScript, although in 0.x the tests were written in CoffeeScript and ran with mocha.

In the long run, Atom is open source, so at the very least it should be possible to get apm to look at the transpiler config while running tests, if it doesn't already. There are probably a couple of angles from which to approach the idea, so we've got plenty of options to explore.

**Comment by smhxx** [comment]
After all, this is only the second transpiler package for Atom, so it's still a relatively unexplored space. I'm sure we're bound to run into a few potential enhancements to Atom/apm along the way.

**Comment by YashdalfTheGray** [comment]
@smhxx oh yeah, shoot, I wasn't too clear with it either and I realized that after I posted the comment. I'm trying to test the package code which I've been using `atom --test spec` as the command but TIL about `apm test`. As for the Typescript `apm` integration and making Atom generally more typescript friendly, I totally agree that we have plenty of options to explore in that space. 

Long time Atom user but I just got into looking at hacking on Atom so all of this is a bit new to me but I'm hoping to be able to contribute where and how I can! Hopefully, sometime in the future, I can even get a package under my name 😃

**Comment by smhxx** [comment]
Hah, if I had thought about it, I probably would have realized what you were referring to. I've just been working on fleshing out the test suite for this package and setting up the test coverage integrations, so my brain was totally in `npm test` mode. Completely slipped my mind that Atom has its own built-in package testing.

To be honest, I'm relatively new to Atom modding myself, although poking around the codebase and interacting with people who know what they're doing has helped me find my feet rather quickly. This all started with a package I was working on to help me build and deploy a certain kind of TypeScript project in a more streamlined way... then I got mildly annoyed at the fact that `linter-tslint` didn't have a feature that I wanted, so I implemented it and opened a PR... then I got to talking to the maintainers about the transpiler feature of Atom and how underused it is (aside from the developer-made Babel transpiler.) We were surprised nobody had made one for TypeScript yet, so I went ahead and threw something together... didn't really expect it to gain as much traction as it's beginning to. It also helps that Glen basically singlehandedly rewrote the entire out-of-date `@types/atom` defs. The timing was pretty great on that. 😄

**Comment by GlenCFL** [comment]
I've created an example as to how to get Atom testing working both within the editor and on the command line [here](https://github.com/GlenCFL/transpiler-testing). It's just a minimal example using a few loose files from an older project of mine for the actual tests.

**Comment by YashdalfTheGray** [comment]
@GlenCFL Ooh the mocha stuff looks very promising, as soon as I can get past this Typescript <1.5 issue, which I still can't see anything in the code for this package that would invoke the wrong transpiler or the wrong version. Like I said, I checked my `package-lock` and only the latest version of Typescript is included. 

Not really sure where to go on this from here. @smhxx you mentioned about a day ago of some workaround that involves clearing the Atom cache or something, how would I go about doing that or should I not do that since it might hide the problem entirely from us. I'm happy to pause messing around with Atom packages until you have some thoughts on how to proceed. Got plenty of other projects to tinker with 😃

**Comment by GlenCFL** [comment]
Probably the compiler cache, which I think would be within ```~/.atom/compile-cache``` on macOS. It's safe to just delete that entire directory, since Atom will just recompile everything.

I kind of want to know how debugging within Atom is on OSX, since it's a nightmare for me on both Windows and Linux.

**Comment by smhxx** [comment]
I'm currently hacking about on the `test-coverage` branch, and it's motivated me to go back and verify that my tests for `getCacheKeyData()` are actually set up properly... they probably are, but I'm second guessing myself now, and it's plausible that a screw-up in that function could cause caching problems. I'm gonna head over to `atom/atom` and make sure that my function signatures are actually in-line with what Atom is expecting. Will update in a moment.

**Comment by smhxx** [comment]
Well, I don't know if this has anything to do with #8, but I just realized that passing compiler options from the `atomTranspilers` entry in package.json has been completely broken since 1.0.0... *oops*. Guess I gotta... y'know, go ahead and fix that. And correct the docs. 😆

I guess 1.2.0 is coming sooner than expected. It's like Christmas coming early this year. 🎉🙌

**Comment by GlenCFL** [comment]
@YashdalfTheGray could you put a ```debugger;``` statement at the bottom of transpile() and report back?
Path would be node_modules/atom-ts-transpiler/dist/index.js.

I imagine it's exactly the same issue that I had and that this will actually fire.

**Comment by GlenCFL** [comment]
@smhxx cacheKeyFiles doesn't work either, unless you contain it within options:
```ts
{
  "glob": "{src,test}/**/*.ts",
  "transpiler": "atom-ts-transpiler",
  "options": {
    "cacheKeyFiles": [
      "package.json",
      "refresh.txt"
    ]
  }
}
```

**Comment by smhxx** [comment]
Now *that's* interesting. I'm weeding through that part of the code right now to make sure I've got the spec fully correct. I think I had the types of a few parameters wrong and that was causing the weirdness with the package.json config.

**Comment by YashdalfTheGray** [comment]
Uh...so this is weird. I went in and put the `debugger;` statement in my test Atom package and then ran it and it all worked, no error, no whining, no nothing. It pulled in the typescript class correctly, transpiled it, didn't give me any errors and the typescript class worked correctly too. I'm going to continue converting the rest of the project to Typescript and see what happens but I think I'll be successful.

It's just a new day, I haven't done anything different with Atom or the package files. Odd. Something must have changed, Atom must have refreshed it's cache.

**Comment by smhxx** [comment]
Once I finish with this boring test refactoring (#10,) I'm going to start work on #9, which should help greatly with debugging any sort of inconsistent behavior between Atom and `atom-ts-transpiler`. I meant to finish that up tonight and push it out as 1.2.0, but unfortunately running into this new bug has slowed down my progress a bit. lol

**Comment by smhxx** [comment]
@YashdalfTheGray If you run into this problem again, 1.2.0 adds the ability to have `atom-ts-transpiler` write some debugging text to the console (Ctrl+Shift+D) any time a module is transpiled; that should make it more obvious whether the existing transpiled code is being run from the cache, or if it's being re-requested from the transpiler. Hopefully that will help isolate what's going on if the issue returns.

As for your last comment, it sounds like the cached version of that file was "messed up" somehow, although I'm not really sure *why*. Any time you change the source code of a file (e.g. by adding that  `debugger` statement,) it invalidates the cached version and forces the file to be rebuilt. The same thing happens when any of your `cacheKeyFiles` changes. For some reason, the cached version of that file seems to have been "bad," although it's hard to say why, and putting in that `debugger` statement forced a re-build, which fixed the issue.

I think I'm going to go ahead and close this on the assumption that the problem has gone away, although if it pops up again, don't hesitate to reopen it. Thanks for all your help in getting the kinks worked out, I think that `atom-ts-transpiler` is in a pretty solid place right now, and I'll be working on my own project for the next week or so which should help confirm that. Unless I run into any unexpected problems of my own, I suspect that 1.2.0 will be the current version for the foreseeable future. Thanks for contributing! 😉
